[project]
name = "aquapointer"

version = "0.0.1a"

classifiers = [
  "Development Status :: 2 - Pre-Alpha",

  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",

  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
]
